# Generated by Django 5.1.6 on 2025-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled')], default='Registered', max_length=255),
        ),
    ]
