# Generated by Django 5.1.6 on 2025-02-24 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('librarians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium')], default='Standard', max_length=255)),
                ('membership_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Suspended', 'Suspended')], default='Pending', max_length=255)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_by', to='librarians.librarian')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-membership_start_date'],
            },
        ),
    ]
