# Generated by Django 5.1.6 on 2025-03-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_member_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-approval_date'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='date_approved',
            new_name='approval_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_end_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_start_date',
        ),
    ]
