# Generated by Django 5.1.6 on 2025-03-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date'], 'verbose_name_plural': 'Reservations'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_date',
            new_name='reservation_date',
        ),
    ]
