# Generated by Django 5.1.6 on 2025-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book_format',
            field=models.CharField(default='Paperback', max_length=255),
        ),
    ]
