# Generated by Django 5.1.6 on 2025-03-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_book_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-borrow_date'], 'verbose_name_plural': 'Transactions'},
        ),
    ]
