# Generated by Django 5.1.6 on 2025-02-24 13:21

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish')], default='English', max_length=255)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_address', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('available_copies', models.PositiveIntegerField(default=0)),
                ('total_copies', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/%Y%m%d')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Paperback', 'Paperback'), ('Audio Book', 'Audio Book'), ('Ebook', 'Ebook'), ('Hardcover', 'Hardcover')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='books/%Y%m%d')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_files', to='books.book')),
            ],
            options={
                'verbose_name_plural': 'Book Files',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='formats',
            field=models.ManyToManyField(blank=True, to='books.bookformat'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='books.bookgenre'),
        ),
    ]
