# Generated by Django 5.1.6 on 2025-03-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookformat',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Book Formats'},
        ),
    ]
