# Generated by Django 5.1.6 on 2025-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='librarian_image',
            field=models.ImageField(blank=True, null=True, upload_to='librarians/%Y%m%d'),
        ),
    ]
